version: "2"
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  data-volume:
